/// Flutter icons Icon_all
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon_all
///      fonts:
///       - asset: fonts/Icon_all.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Icon_all {
  Icon_all._();

  static const _kFontFam = 'Icon_all';

  static const IconData all_icon = IconData(0xe805, fontFamily: _kFontFam);
}
